plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - arm64
    - x86
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.2.2.cjs
